// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(RelationshipDbContext))]
    [Migration("20250518190346_description column for character")]
    partial class descriptioncolumnforcharacter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_character");

                    b.ToTable("character");
                });

            modelBuilder.Entity("Entities.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RelationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("relation_type_id");

                    b.Property<int>("SourceCharacterId")
                        .HasColumnType("int")
                        .HasColumnName("source_character_id");

                    b.Property<int>("TargetCharacterId")
                        .HasColumnType("int")
                        .HasColumnName("target_character_id");

                    b.HasKey("Id")
                        .HasName("pk_connection");

                    b.HasIndex("RelationTypeId")
                        .HasDatabaseName("ix_connection_relation_type_id");

                    b.HasIndex("TargetCharacterId")
                        .HasDatabaseName("ix_connection_target_character_id");

                    b.HasIndex("SourceCharacterId", "TargetCharacterId")
                        .IsUnique()
                        .HasDatabaseName("ix_connection_source_character_id_target_character_id");

                    b.ToTable("connection");
                });

            modelBuilder.Entity("Entities.ConnectionNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int")
                        .HasColumnName("connection_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("content");

                    b.HasKey("Id")
                        .HasName("pk_connection_note");

                    b.HasIndex("ConnectionId")
                        .HasDatabaseName("ix_connection_note_connection_id");

                    b.ToTable("connection_note");
                });

            modelBuilder.Entity("Entities.RelationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_relation_type");

                    b.ToTable("relation_type");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Entities.Connection", b =>
                {
                    b.HasOne("Entities.RelationType", "RelationType")
                        .WithMany()
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connection_relation_type_id_relation_type");

                    b.HasOne("Entities.Character", "SourceCharacter")
                        .WithMany("SourceConnections")
                        .HasForeignKey("SourceCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_connection_source_character_id_character");

                    b.HasOne("Entities.Character", "TargetCharacter")
                        .WithMany("TargetConnections")
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connection_target_character_id_character");

                    b.Navigation("RelationType");

                    b.Navigation("SourceCharacter");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("Entities.ConnectionNote", b =>
                {
                    b.HasOne("Entities.Connection", "Connection")
                        .WithMany("Notes")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connection_note_connection_id_connection");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Entities.Character", b =>
                {
                    b.Navigation("SourceConnections");

                    b.Navigation("TargetConnections");
                });

            modelBuilder.Entity("Entities.Connection", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
